version: '3.8'

x-exp-vol: &exp-vol
  volumes:
    - ./fault_tolerance/ft_node_loss_single/results:/app/results

services:
  # 保持與 original 名稱一致，僅覆寫必要配置
  fl-server:
    <<: *exp-vol
    # 可視需要提高日誌詳細度或掛載額外 volume

  fl-participant-1:
    <<: *exp-vol
  fl-participant-2:
    <<: *exp-vol
  fl-participant-3:
    <<: *exp-vol
  fl-participant-4:
    <<: *exp-vol
  fl-participant-5:
    <<: *exp-vol
  fl-participant-6:
    <<: *exp-vol
  fl-participant-7:
    <<: *exp-vol
  fl-participant-8:
    <<: *exp-vol
  fl-participant-9:
    <<: *exp-vol
  fl-participant-10:
    <<: *exp-vol
  fl-participant-11:
    <<: *exp-vol
  fl-participant-12:
    <<: *exp-vol
  fl-participant-13:
    <<: *exp-vol
  fl-participant-14:
    <<: *exp-vol
  fl-participant-15:
    <<: *exp-vol
  fl-participant-16:
    <<: *exp-vol 